Explorer:
  ros__parameters:
    aruco_detect: True
    num_aruco_markers: 2
    debug: True

amcl:
  ros__parameters:
    set_initial_pose: true
    initial_pose: 
      x: 0.0
      y: 0.0
      yaw: 1.0
